TaskController/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from main.views import main
from main.views import register
from main.views import add_user
from main.views import login_view
from Tasks.views import task
from Tasks.views import new_task
from Tasks.views import new_message
from Tasks.views import edit_task
from users.views import department
from users.views import new_dep


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$',main),
    url(r'^register$', register),
    url(r'^add_user$', add_user),
    url(r'^bundles$', task),
    url(r'new_project', new_task),
    url(r'new_message', new_message),
    url(r'department', department),
    url(r'new_dep', new_dep),
    url(r'login', login_view),
    url(r'edit_task$', edit_task),
    url(r'^admin/', include(admin.site.urls)),

)

Tasks/models.py
from django.db import models
from django.contrib import admin
from users.models import Worker

class Task(models.Model):

    STATUS_CHOICES = (
        (1,"Normal"),
        (2,"High"),
        (3,"Urgent"),
        (4,"Immediate"),
        (5,"Failed"),
        (6,"Succeed")
        )

    TYPE_CHOICE = (
        (1,"Project"),
        (2,"Separate task"),
        (3,"Sub task")
        )

    title = models.CharField(max_length=50)
    description = models.TextField()

    start_date =  models.DateField()
    end_date = models.DateField()

    status = models.PositiveIntegerField(choices=STATUS_CHOICES, default=1)
    type = models.PositiveIntegerField(choices=TYPE_CHOICE, default=2)

    parent = models.ForeignKey("self", blank=True,
                               null=True, related_name="root")
    performer = models.ManyToManyField(Worker, null=True,
                                       blank=True, related_name='workers')
    manager = models.ForeignKey(Worker, related_name='manager')

    def change_type(self, var):
        self.type = var

    def change_status(self, var):
        self.status = var

    def get_rel_task(self):
        return Task.objects.filter(parent = self)

    def all_rel_task(self):
        rel = []
        rel.append(self)
        for task in Task.objects.filter(parent = self):
            rel.append(task.all_rel_task)
        return rel

    def set_performer(self, _id):
        self.performer = Worker.objects.get(id=_id)

    def add_task(self, _id):
        self.tasks = Task.objects.get(id = _id)

    def get_workers(self):
        task = Task.objects.get(id = self.id)
        return task.performer.all()

    def get_message(self):
        return Message.objects.filter(rel_task = self)

    def save(self, *args, **kwargs):
        if self.parent is None:
            self.type = 2
        else:
            self.type = 3
            self.parent.type = 1
            self.parent.save()
        super(Task, self).save(*args, **kwargs)


    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = ('title', 'parent')


class Message(models.Model):
    sender = models.ForeignKey(Worker, null=False, related_name='sender')
    rel_task = models.ForeignKey(Task, null=False, related_name='task')
    title = models.CharField(max_length=30)
    description = models.TextField()
    date = models.DateField()

admin.site.register(Task)
admin.site.register(Message)

users/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.contrib import admin

class Worker(models.Model):
    ROLE = (
        (1, "Project Manager"),
        (2, "Programmer")
    )

    user = models.OneToOneField(User)
    role = models.PositiveIntegerField(choices=ROLE, default=2)

    def __str__(self):
        return self.user.username


class Department(models.Model):
    name = models.CharField(max_length=30)
    owner = models.OneToOneField(Worker)
    access = models.OneToOneField(Group)
    workers = models.ManyToManyField(Worker, blank=True,
                                     null=True, related_name='employers')
    sub_dep = models.ForeignKey("self",blank=True, null=True)

    def get_workers(self):
        worker = Worker.objects.get(id = self.id)
        return worker.workers.all()
    def __str__(self):
        return self.name

admin.site.register(Worker)
admin.site.register(Department)

Tasks/forms.py
__author__ = 'Toaster'
from django import forms
from Tasks.models import Task
from Tasks.models import Message
from django.forms import ModelForm


class ProjectForm(ModelForm):
    class Meta:
        model = Task
        exclude = ('type')

class EditProjectForm(ModelForm):
    class Meta:
        model = Task
        exclude = ("type", "parent", "start_date", "manager")


class MessageForm(ModelForm):
    class Meta:
        model = Message

Tasks/views.py
from django.shortcuts import render_to_response, redirect
from Tasks.models import Task
from Tasks.forms import ProjectForm
from Tasks.forms import MessageForm
from Tasks.forms import EditProjectForm

__id__ = 0

def task(request):
    tasks = Task.objects.all()
    return render_to_response("Task/project.html",{'tasks': tasks})

def new_task(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ProjectForm(request.POST) # A form bound to the POST data
        if form.is_valid():
            form.save(commit=True)
            return redirect("/bundles") # Redirect after POST
        else:
            return render_to_response("Task/create_project.html", {'form': form,})
    else:
        form = ProjectForm()
        return render_to_response("Task/create_project.html", {
            'form': form,
            })

def new_message(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return render_to_response("Task/message.html")
        else:
            return render_to_response("Task/new_message.html", {'form': form,})
    else:
        form = MessageForm()
        return render_to_response("Task/new_message.html", {'form' : form,})

def edit_task(request):
    if 'task_id' in request.POST:
        global __id__
        __id__ = request.POST['task_id']
        curr_task = Task.objects.get(id = __id__)
        form = EditProjectForm(instance = curr_task)
        return render_to_response("Task/edit_task.html", {'form' : form},)
    else:
        form = EditProjectForm(request.POST, instance=Task.objects.get(id = __id__))
        if form.is_valid:
            form.save()
            return redirect("/bundles")
        else:
            return  render_to_response("Task/edit_task.html", {'form' : form})

templates/Task/create_project.html
{% extends "main.html" %}
<html>
<head>
    <title></title>
</head>
<body>

    {% block main %}
        <div class="span9">
        <div class="hero-unit">
            <form method="post" action="/new_project">
            {% for field in form %}
                {{ field.label_tag }}{{ field }}
                {{ field.errors }}
            {% endfor %}
            {{ field.non_form_errors }}
            <br>
                <input type="submit">
            </form>
        </div>
        </div>
    {% endblock %}

</body>
</html>

templates/Task/edit_task.html
{% extends "main.html" %}
<html>
<head>
    <title></title>
</head>
<body>

{% block main %}
    <div class="span9">
        <div class="hero-unit">
            <form method="post" action="/edit_task">
                {% for field in form %}
                    {{ field.label_tag }}{{ field }}
                    {{ field.errors }}
                {% endfor %}
                {{ field.non_form_errors }}
                <br>
                <input type="submit">
            </form>
        </div>
    </div>
{% endblock %}

</body>
</html>

templates/Task/employer.html
<script type="text/javascript" src="/static/bootstrap/js/jquery.js"></script>
<script type="text/javascript" src="/static/bootstrap/js/bootstrap-collapse.js"></script>
<div class="tab-pane" id="employer">
    <h3>Workers</h3>
    {% for task in tasks %}
        {% for work in task.get_workers %}
            <div class="accordion" id="accordion2">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse{{ work.id }}">
                            <span class="badge badge-info"> {{ work.user.username }}</span>
                        </a>
                    </div>
                    <div id="collapse{{ work.id }}" class="accordion-body collapse in" style="height: 0px; ">
                        <div class="accordion-inner">
                            <table class="table">
                                <tbody>
                                {{ work.get_role_display }}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endfor %}
</div>

templates/Task/message.html
<script type="text/javascript" src="/static/bootstrap/js/jquery.js"></script>
<script type="text/javascript" src="/static/bootstrap/js/bootstrap-collapse.js"></script>
<div class="tab-pane" id="messages">
    <h3>Message</h3>
    {% for task in tasks %}
        {% for message in task.get_message %}

           <table>
                <thead>
                {{ message.title }}
                </thead>
                <tbody>
                <hr>
                {{ message.description }}
                </tbody>
            </table>
        {% endfor %}
    {% endfor %}

    <submit class="btn"><a href="new_message">New message</a></submit>
</div>

templates/Task/new_message.html
{% extends "main.html" %}
<html>
<head>
    <title></title>
</head>
<body>

{% block main %}
    <div class="span9">
        <div class="hero-unit">
            <form method="post" action="/new_message">
                {% for field in form %}
                    {{ field.label_tag }}{{ field }}
                    {{ field.errors }}
                {% endfor %}
                {{ field.non_form_errors }}
                <br>
                <input type="submit">
            </form>
        </div>
    </div>
{% endblock %}

</body>
</html>

templates/Task/project.html
{% extends "main.html" %}
<html>
<head>
    <title></title>
</head>
<body>
    {% block main %}
        <link rel="stylesheet" type="text/css" href="/static/css/template.css" />
        <div id="content">
            <ul class="nav nav-tabs" data-tabs="tabs">
                <li class="active"><a href="#project">Projects</a></li>
                <li><a href="#task">Tasks</a></li>
                <li><a href="#employer">Employers</a></li>
                <li><a href="#messages">Messages</a></li>
            </ul>
            <div id="my-tab-content" class="tab-content">
                <div class="tab-pane active" id="project">
                      {% for task in tasks %}
                          <div class="task_wrapper">

                                <div class="title">
                <form name="myform" method="POST" action="/edit_task">
                <A HREF="javascript: submitform();">
                    {{ task.title }}
                </A>
                <input type="hidden" name="task_id" value="{{ task.id }}">
                </form>

                <script type="text/javascript">
                    function submitform()
                    {
                        document.myform.submit();
                    }
                </script>
                                </div>

                                <div class="description">
                                {{ task.description }}
                                </div>

                                <div class="priority">
                                Priority: {{ task.get_status_display }}
                                </div>

                                <div class="end_date">
                                {{ task.end_date }}
                                </div>
                          </div>
                        {% endfor %}
                </div>

                {% include "Task/task.html" %}
                {% include "Task/employer.html" %}
                {% include "Task/message.html" %}

            </div>
        </div>

        {% block scripts %}
        <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/static/bootstrap/js/bootstrap-tabs.js"></script>
        <script type="text/javascript" src="/static/bundle/bundle.js"></script>

        <script type="text/javascript">
            jQuery(document).ready(function ($) {
                var _switch = $(".priority").text().split(":")[1].trim();
                get_status( _switch );
                $(".tabs").tabs();
            });
        </script>
        {% endblock %}

    {% endblock %}
</body>
</html>

templates/Task/task.html
<script type="text/javascript" src="/static/bootstrap/js/jquery.js"></script>
<script type="text/javascript" src="/static/bootstrap/js/bootstrap-collapse.js"></script>
<div class="tab-pane" id="task">
    <h3>Relative tasks</h3>
    {% for task in tasks %}
        {% for rel in task.get_rel_task %}
            <div class="accordion" id="accordion2">
                <div class="accordion-group">

                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse{{ rel.id }}">
                            <span class="badge badge-info"> {{ rel.title }}</span>
                        </a>
                    </div>

                    <div id="collapse{{ rel.id }}" class="accordion-body collapse in" style="height: 0px; ">
                        <div class="accordion-inner">
                            <table class="table">
                                <thead>
                                    {{ rel.description }}
                                </thead>
                                <tbody>
                            <hr>
                            {{ rel.start_date }} - {{ rel.end_date }}
                            <br>
                            {{ rel.manager.user.username }}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endfor %}
</div>